name: TripWire
main: no.runsafe.tripwire.Plugin
version: 1.0.@BUILD@
authors: [mortenn]
description: Plugin to detect hackers on the server

permissions:
  tripwire.notify:
    description: Receive notifications from tripwire
    default: false